### ISSUE TITLE
Mentee Settings Page

### ISSUE THREAD

**Issue by mentorme-intech** [mentormeintech/mmit-webapp-vite#33]
A page is needed for the mentee settings page, the page should have a route name of mentee-settings. The folder structure should be mentorsettings as folder and page.jsx as file name

**Comment by mentorme-intech** [comment]
The folder structure should be mentorsupport as folder and page.jsx as file name

**Comment by mruqqie** [comment]
@dolaposokoya What endpoint will the settings be saved to?

**Comment by dolaposokoya** [comment]
I don't understand you.
