### ISSUE TITLE
Mentee Support Page

### ISSUE THREAD

**Issue by mentorme-intech** [mentormeintech/mmit-webapp-vite#34]
A page is needed for the mentee support page, the page should have a route name of mentee-support. The folder structure should be mentorsupport as folder and page.jsx as file name

**Comment by segunajibola** [comment]
added the page - pull request #36

**Comment by mentorme-intech** [comment]
@segunajibola I can't find the page, I might have replaced it, do you still have the source code with you? if yes please make a pull request again. Thank you

**Comment by mentorme-intech** [comment]
@segunajibola Create the content for the Support page, follow what the mentor's page has 
<img width="1440" alt="Screenshot 2024-02-23 at 4 03 06 PM" src="https://github.com/mentormeintech/mmit-webapp-vite/assets/138000300/cc03bd71-9882-4003-b48f-c0bc89c1c074">

**Comment by segunajibola** [comment]
okay
