### ISSUE TITLE
Create update mentor endpoint

### ISSUE THREAD

**Issue by mentorme-intech** [mentormeintech/mmit-webapp-vite#74]
Create an endpoint that allows the mentor to update some details on their profile

![Screen Shot 2024-11-10 at 8 56 50 PM](https://github.com/user-attachments/assets/670332d8-a8c7-44c3-8691-a6ccf6b05701)
![Screen Shot 2024-11-10 at 8 57 08 PM](https://github.com/user-attachments/assets/cda5eebd-5e70-429a-979d-a2465fcf49da)

The same endpoint can be used here, the key and value are what changes and also the update password should be a different endpoint.

And for every endpoint go through the route first to make sure the endpoint doesn't exist and later the controller to see if the function is available but not linked.

Thank you.

**Comment by mdauwal** [comment]
Well received with thanks.

**Comment by mdauwal** [comment]
Good morning bro, I could not find the env file for backend
